subdivision/urls.py
from django.urls import path

from subdivision import views

urlpatterns = [
    # event
    path('addevent', views.add_event, name='addevent'),
    path('view', views.eventview, name='rempla'),
    path('list', views.EventList.as_view(), name='event_list'),
    path('detail/<int:pk>', views.EventDetail.as_view(), name='event_detail'),
    path('events.json', views.events_json, name='events.json'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('create/<str:start>/<str:end>', views.create, name='create'),
    path('resize/<int:id>/<str:end>', views.resize, name='resize'),
    path('drop/<int:id>/<str:start>/<str:end>', views.drop, name='drop'),
    path('eventupdate/<int:pk>', views.eventupdate, name='eventupdate'),
    path('eventdetail/<int:pk>', views.EventDetail.as_view(), name='eventdetail'),
    path('eventdelete/<int:pk>', views.eventdelete, name='eventdelete'),
    # rpt
    path('rpt', views.RptList.as_view(), name='rpt_list'),
    path('rptdetail/<int:pk>', views.RptDetail.as_view(), name='rpt_detail'),
    path('rptupdate/<int:pk>', views.RptUpdate.as_view(), name='rpt_update'),
    path('rptdelete/<int:pk>', views.RptDelete.as_view(), name='rpt_delete'),
    path('rptcreate', views.RptCreate.as_view(), name='rpt_create'),
    # pdf
    path('editpdf/<int:id>', views.edit_pdf, name='editpdf'),
    path('monthpdf/<annee>/<mois>', views.pdf_month, name='monthpdf'),
    path('eventpdf/<int:are>/<int:rpt>/<int:event>', views.pdf_event, name='eventpdf'),
    path('searchrptmonth', views.searchrptmonth, name='searchrptmonth'),
    path('searchMonth', views.searchMonth, name='searchMonth'),
    path('archives', views.archive, name='archives'),
    path('upload/<str:arch>', views.upload, name='upload'),
    # crud ajax rpt
    path('crud_rpt/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudRpt.as_view(), name='crud_ajax_create'),
    path('ajax/crud/update/', views.UpdateCrudRpt.as_view(), name='crud_ajax_update'),
    path('ajax/crud/delete/', views.DeleteCrudRpt.as_view(), name='crud_ajax_delete'),
    path('ajax/crud/edit/', views.EditCrudRpt.as_view(), name='crud_ajax_edit'),
    path('index', views.index, name='index'),
    path('ajax_calls/search', views.autocompleteModel, name='search'),
    # are
    path('are', views.AreList.as_view(), name='are_list'),
    path('aredetail/<int:pk>', views.AreDetail.as_view(), name='are_detail'),
    path('areupdate/<int:pk>', views.AreUpdate.as_view(), name='are_update'),
    path('aredelete/<int:pk>', views.AreDelete.as_view(), name='are_delete'),
    path('arecreate', views.AreCreate.as_view(), name='are_create'),
    # iade
    path('iade', views.IadeList.as_view(), name='iade_list'),
    path('iadedetail/<int:pk>', views.IadeDetail.as_view(), name='iade_detail'),
    path('iadeupdate/<int:pk>', views.IadeUpdate.as_view(), name='iade_update'),
    path('iadedelete/<int:pk>', views.IadeDelete.as_view(), name='iade_delete'),
    path('iadecreate', views.IadeCreate.as_view(), name='iade_create'),

]

subdivision/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.urls import reverse


class HopParam(models.Model):
    name = models.CharField(max_length=100)
    adress1 = models.CharField(max_length=100)
    adress2 = models.CharField(max_length=100, blank=True, null=True)
    town = models.CharField(max_length=100)
    postalcode = models.CharField(max_length=5)
    cedex = models.CharField(max_length=10, blank=True, null=True)
    finess = models.CharField(max_length=10, blank=True, null=True)
    logo = models.ImageField(upload_to='hop', blank=True, null=True)
    tel = models.CharField(max_length=10, blank=True, null=True)
    fax = models.CharField(max_length=10, blank=True, null=True)
    villes = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Hôpital'
        verbose_name_plural = 'Hôpitaux'
        ordering = ['name']


class WebColor(models.Model):
    color = models.CharField(max_length=30, verbose_name='Couleur')
    colorHex = models.CharField(max_length=10, verbose_name='Hexa')

    def __str__(self):
        return self.color

    class Meta:
        verbose_name = 'Couleurs Web'
        ordering = ['color']


class Calendrier(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=True, blank=True)
    color = models.ForeignKey(WebColor, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Calendrier'
        verbose_name_plural = 'Calendriers'
        ordering = ['name']


class Are(models.Model):
    SECTOR = (
        ('1', 'Secteur 1'),
        ('2', 'Secteur 2'),
    )

    name = models.CharField(max_length=50, verbose_name='Nom')
    forname = models.CharField(max_length=50, verbose_name='Prénom')
    adress1 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Adresse')
    adress2 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Complément adresse')
    town = models.CharField(max_length=50, blank=True, null=True, verbose_name='Ville')
    coNum = models.CharField(max_length=20, blank=True, null=True, verbose_name='Numéro CO')
    rpps = models.CharField(max_length=20, blank=True, null=True, verbose_name='Rpps')
    postalcode = models.CharField(max_length=5, blank=True, null=True, verbose_name='Code postal')
    telmob = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Mobile')
    tel2 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Perso.')
    phone_hop = models.CharField(max_length=12, verbose_name='Poste', blank=True, null=True)
    phone_secretary = models.CharField(max_length=12, verbose_name='Secrétariat', null=True, blank=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    secteur = models.CharField(max_length=10, choices=SECTOR, verbose_name='Secteur', default=True, blank=True,
                               null=True)
    photo = models.ImageField(upload_to='are/photo', blank=True, null=True)
    signature = models.ImageField(upload_to='are/signature', blank=True, null=True)
    codepartname = models.CharField(max_length=50, blank=True, null=True)
    codepartnum = models.CharField(max_length=5, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('are_detail', kwargs={'pk': self.pk})

    @property
    def initials(self):
        return self.forname[2] + '.' + self.name[2]

    def __str__(self):
        return self.name + ' ' + self.forname

    class Meta:
        verbose_name = "Anesthésiste"
        verbose_name_plural = "Anesthésistes"
        ordering = ['name', ]


BOOL = (
    ('Oui', 'Oui'),
    ('Non', 'Non'),
)


class Rpt(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nom')
    forname = models.CharField(max_length=50, verbose_name='Prénom')
    adress1 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Adresse')
    adress2 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Complément d\'adresse')
    town = models.CharField(max_length=50, blank=True, null=True, verbose_name='Ville')
    codepartname = models.CharField(max_length=50, blank=True, null=True, verbose_name='Nom Départ. CO')
    codepartnum = models.CharField(max_length=10, blank=True, null=True, verbose_name='Num. Départ. CO')
    conum = models.CharField(max_length=50, blank=True, null=True, verbose_name='Num. CO')
    rpps = models.CharField(max_length=20, blank=True, null=True, verbose_name='Num. RPPS')
    urssafnum = models.CharField(max_length=50, blank=True, null=True, verbose_name='URSSAF')
    sirennum = models.CharField(max_length=50, blank=True, null=True, verbose_name='Siren')
    postalcode = models.CharField(max_length=10, blank=True, null=True, verbose_name='Code postal')
    telmob = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Mobile')
    tel2 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Perso')
    tel3 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Travail')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='Email')
    status = models.CharField(max_length=3, choices=BOOL, verbose_name='Thésé', blank=True, null=True)
    photo = models.ImageField(upload_to='rpt/photo', blank=True, null=True, verbose_name='Photo')
    assurance = models.FileField(upload_to='rpt/assurance', blank=True, null=True, verbose_name='Assurance')
    licence = models.FileField(upload_to='rpt/licence', blank=True, null=True, verbose_name='Licence')
    licence_exp_date = models.DateField(verbose_name='Date expiration licence', blank=True, null=True)
    active = models.CharField(max_length=3, choices=BOOL, verbose_name="Actif", blank=True, null=True)
    signature = models.ImageField(upload_to='rpt/signature', blank=True, null=True, )

    def get_absolute_url(self):
        return reverse('rpt_detail', kwargs={'pk': self.pk})

    @property
    def initials(self):
        return self.forname[2] + '.' + self.name[2]

    def __str__(self):
        return self.name + ' ' + self.forname

    class Meta:
        verbose_name = "Remplaçant"
        verbose_name_plural = "Remplaçants"
        ordering = ['name', ]
        unique_together = ['name', 'forname']


class Compta(models.Model):
    rpt_cost = models.IntegerField(blank=True, null=True, verbose_name='Rpt tarif')
    vac_cost_1 = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, verbose_name='Vac moins')
    vac_cost_2 = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, verbose_name='Vac plus')
    gerant = models.ForeignKey(Are, related_name='gerant', null=True, blank=True, verbose_name='Gerant',
                               on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'Comptabilite'


class Event(models.Model):
    PAYTYPE = (
        ('C', 'Chèque'),
        ('V', 'Virement'),
    )

    type = models.CharField(blank=True, null=True, default='RPT', max_length=10, verbose_name='Type')
    description = models.TextField(max_length=200, null=True, blank=True, default='', verbose_name='Résumé')
    title = models.CharField(max_length=100, default='RPT :  ', verbose_name='Titre')
    start = models.DateField(verbose_name='Début')
    start_time = models.TimeField(verbose_name='Heure début', default='00:00:00')
    end = models.DateField(verbose_name='Fin', null=True, blank=True)
    end_time = models.TimeField(verbose_name='Heure Fin', default='00:00:00')
    calendrier = models.ForeignKey(Calendrier, on_delete=models.CASCADE, blank=True, null=True,
                                   verbose_name='Type édition')
    is_cancelled = models.BooleanField(default=False, blank=True)
    all_day = models.BooleanField(default=True, blank=True)
    are = models.ForeignKey(Are, on_delete=models.DO_NOTHING, related_name='are', verbose_name='Anesthésiste',
                            null=True)
    rpt = models.ForeignKey(Rpt, on_delete=models.DO_NOTHING, related_name='rpt', verbose_name='Remplaçant', null=True)
    pay_date = models.DateField(blank=True, null=True, verbose_name='Date de paiement')
    pay_type = models.CharField(max_length=20, choices=PAYTYPE, blank=True, null=True, verbose_name='Moyen de paiement')
    pay_are = models.ForeignKey(Are, related_name='ArePay', null=True, blank=True, on_delete=models.DO_NOTHING,
                                verbose_name='Payeur')
    pay_amount = models.IntegerField(default=settings.AMOUNT_RPT, blank=True, null=True, verbose_name='Montant')
    pay_numchq = models.CharField(max_length=50, null=True, blank=True, verbose_name='N° chèque')

    def get_absolute_url(self):
        return reverse('event_detail', kwargs={'pk': self.pk})

    @property
    def jend(self):
        return self.end - timedelta(days=1)

    def __str__(self):
        return str(self.start) + ' ' + self.title

    class Meta:
        verbose_name = 'Evènement'
        verbose_name_plural = 'Evènements'
        ordering = ['start', 'end']
        unique_together = [('are', 'start'), ('rpt', 'start')]

subdivision/templates/subdivision/rpt/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4 ml-5">

                <form id="search" method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name"></label>
                        <input class="form-control" type="text" list="rptnames" id="name" name="name" required/>
                        <datalist id="rptnames">
                            {% for rpt in rpts %}
                                <option value={{ rpt }}>
                            {% endfor %}
                        </datalist>
                    </div>
                    <div class="form-group">
                        <label for="mois">Choix du mois</label>
                        <select class="form-control" name="mois" id="mois" required>
                            <option selected disabled value="">----------</option>
                            <option value="01">Janvier</option>
                            <option value="02">Février</option>
                            <option value="03">Mars</option>
                            <option value="04">Avril</option>
                            <option value="05">Mai</option>
                            <option value="06">Juin</option>
                            <option value="07">Juillet</option>
                            <option value="08">Août</option>
                            <option value="09">Septembre</option>
                            <option value="10">Octobre</option>
                            <option value="11">Novembre</option>
                            <option value="12">Décembre</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="annee">Choix de l'année</label>
                        <select class="form-control" name="annee" id="annee" required>
                            <option selected disabled value="">----------</option>
                            {% for an in annees %}
                                <option value={{ an }}>{{ an }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary btn-submit">Envoyez</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subdivision/templates/subdivision/rpt/rpt_create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Nouveau remplaçant{% endblock %}
{% block titre %}Mise à jour{% endblock %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="card  mt-5">
                <div class="card-header font-weight-bold">Remplaçant</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3 text-left">
                            <label for="id_name" class="form-label">Nom</label>
                            {{ form.name|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_forname" class="form-label">Prénom</label>
                            {{ form.forname|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_telmob" class="form-label">Tél. mobile</label>
                            {{ form.telmob|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_email" class="form-label">Email</label>
                            {{ form.email|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Adresse</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_adress1" class="form-label">Adresse</label>
                                {{ form.adress1|attr:"class:form-control" }}
                                <label for="id_adress2" class="form-label mt-2">Complément d'adresse</label>
                                {{ form.adress2|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_postalcode" class="form-label">Code postal</label>
                                {{ form.postalcode|attr:"class:form-control" }}
                                <label for="id_town" class="form-label mt-2">Ville</label>
                                {{ form.town|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_tel2" class="form-label">Tél. fixe</label>
                                {{ form.tel2|attr:"class:form-control" }}
                                <label for="id_tel3" class="form-label mt-2">Tél. autre</label>
                                {{ form.tel3|attr:"class:form-control" }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Administration</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_status" class="form-label">Statut</label>
                                {{ form.status|attr:"class:form-control" }}
                                <label for="id_conum" class="form-label mt-2">N° CO</label>
                                {{ form.conum|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_codepartname" class="form-label">Nom département</label>
                                {{ form.codepartname|attr:"class:form-control" }}
                                <label for="id_codepartnum" class="form-label mt-2">Numéro département</label>
                                {{ form.codepartnum|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_rpps" class="form-label">Numéro RPPS (si thésé)</label>
                                {{ form.rpps|attr:"class:form-control" }}
                                <label for="id_active" class="form-label mt-2">Actif</label>
                                {{ form.active|attr:"class:form-control" }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-sm-3">
                    <div><input class="btn btn-success pull-left" type="submit" value="Envoyer"/></div>
                </div>
                <div class="col-sm-3">
                    <div><a href="{% url 'rpt_list' %}" class="btn btn-info pull-left"
                            role="button">Annuler</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

subdivision/templates/subdivision/rpt/rpt_detail.html
{% extends "base.html" %}
{% block title %}Détail d'un remplaçant{% endblock %}
{% block extrahead %}
{% endblock %}
{% block titre %}Fiche de {{ object.forname|title }} {{ object.name|upper }}{% endblock %}>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-5 text-left">
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Détail
                        de {{ object.forname|title }} {{ object.name|upper }}
                        <span class="ml-5">Actif : {% if object.active != None %}Non{% endif %}</span>
                    </div>
                    <div class="card-body">
                        <p>Nom : {{ object.name|upper }}</p>
                        <p>Prénom : {{ object.forname|title }}</p>
                        <p>Mobile : {{ object.telmob }}</p>
                        <p>Email : <a href="mailto:{{ object.email }}">{{ object.email }}</a></p>
                    </div>
                </div>
            </div>
            <div class="col-5 text-left">
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Statut : {{ object.status|title }}
                    </div>
                    <div class="card-body">
                        <p>Adresse : {{ object.adress1|title }}</p>
                        <p>Complément : {% if object.adress2 %}{{ object.adress2|title }}{% else %}-{% endif %}</p>
                        <p>Code postal : {{ object.postalcode }}</p>
                        <p>Ville : {{ object.town }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-5 text-left">
                <div class="card  mt-2">
                    <div class="card-header font-weight-bold">Conseil de l'Ordre</div>
                    <div class="card-body">
                        <p>Num. CO : {{ object.conum }}</p>
                        <p>Département CO : {{ object.codepartname|title }}</p>
                        <p>Code : {{ object.codepartnum }}</p>
                        <p>Date expiration licence : {{ object.licence_exp_date|date:'d/m/Y' }}</p>
                    </div>
                </div>
            </div>
        </div>
    <a href="{% url 'rpt_list' %}" class="btn btn-primary pull-left mt-5"
                           role="button">Retour</a>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

subdivision/templates/subdivision/rpt/rpt_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Mise à jour d'un remplaçant{% endblock %}
{% block titre %}Mise à jour{% endblock %}
{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card  mt-3">
                <div class="card-header font-weight-bold justify-content-between">
                    <div class="row">
                        <div class="'col-2 ml-3 h4">
                            Contact
                        </div>
                            <label for="id_active" class="col-sm-2 offset-2 col-form-label float-right"></label>
                        <div class="col-sm-4 float-left">
                            {{ form.active|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3 text-left">
                            <label for="id_name" class="form-label">Nom</label>
                            {{ form.name|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_forname" class="form-label">Prénom</label>
                            {{ form.forname|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_telmob" class="form-label">Tél. mobile</label>
                            {{ form.telmob|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_email" class="form-label">Mail</label>
                            {{ form.email|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
                <div class="card  mt-3">
                    <div class="card-header font-weight-bold">Adresse</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_adress1" class="form-label">Adresse</label>
                                {{ form.adress1|attr:"class:form-control" }}
                                <label for="id_adress2" class="form-label mt-2">Complément d'adresse</label>
                                {{ form.adress2|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_postalcode" class="form-label">Code Postal</label>
                                {{ form.postalcode|attr:"class:form-control" }}
                                <label for="id_town" class="form-label mt-2">Ville</label>
                                {{ form.town|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_tel2" class="form-label">Tél.</label>
                                {{ form.tel2|attr:"class:form-control" }}
                                <label for="id_tel3" class="form-label mt-2">Tél.</label>
                                {{ form.tel3|attr:"class:form-control" }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header font-weight-bold">Administration</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_status" class="form-label">Thésé(e)</label>
                                {{ form.status|attr:"class:form-control" }}
                                <label for="id_conum" class="form-label mt-2">Numéro CO</label>
                                {{ form.conum|attr:"class:form-control" }}
                                <label for="id_rpps" class="form-label mt-2">RPPS</label>
                                {{ form.rpps|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_licence_exp_date" class="form-label">Date expiration licence</label>
                                {{ form.licence_exp_date|attr:"class:form-control" }}
                                <label for="id_codepartname" class="form-label mt-2">Nom département</label>
                                {{ form.codepartname|attr:"class:form-control" }}
                                <label for="id_codepartnum" class="form-label mt-2">Code département</label>
                                {{ form.codepartnum|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-6 text-left">
                                <label for="id_assurance" class="form-label">Assurance</label>
                                {{ form.assurance|attr:"class:form-control" }}
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-sm-3">
                                <div><input class="btn btn-success pull-left" type="submit" value="Envoyer"/></div>
                            </div>
                            <div class="col-sm-3">
                                <div><a href="{% url 'rpt_list' %}" class="btn btn-info pull-left"
                                        role="button">Annuler</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}
    <script>
        $.datetimepicker.setLocale('fr');
        $(document).ready(function () {
            jQuery('#id_licence_exp_date').datetimepicker({
                timepicker: false,
                dayOfWeekStart: 1,
                format: 'd/m/Y',

            });
        });
    </script>
{% endblock %}

subdivision/templates/subdivision/rpt/select.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/select2/select2.css' %}" rel="stylesheet"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="card mt-5">
            <div class="card-header">Choix du remplaçant</div>
            <div class="card-body">
                <form>
                    <div class="form-group">
                        <label for="e1">Remplaçant</label>
                        <select class="form-control" id="e1" name="rpt">
                            <option value="">----------</option>
                            {% for item in items %}
                                <option value={{ item.id }}>{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Example select</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option value="">----------</option>
                            {% for item in items %}
                                <option value={{ item.id }}>{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/select2/select2.full.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#e1').select2();
    });
</script>
</body>
</html>