subdivision/urls.py
from django.urls import path

from subdivision import views

urlpatterns = [
    # event
    path('addevent', views.add_event, name='addevent'),
    path('view', views.eventview, name='rempla'),
    path('list', views.EventList.as_view(), name='event_list'),
    path('detail/<int:pk>', views.EventDetail.as_view(), name='event_detail'),
    path('events.json', views.events_json, name='events.json'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('create/<str:start>/<str:end>', views.create, name='create'),
    path('resize/<int:id>/<str:end>', views.resize, name='resize'),
    path('drop/<int:id>/<str:start>/<str:end>', views.drop, name='drop'),
    path('eventupdate/<int:pk>', views.eventupdate, name='eventupdate'),
    path('eventdetail/<int:pk>', views.EventDetail.as_view(), name='eventdetail'),
    path('eventdelete/<int:pk>', views.eventdelete, name='eventdelete'),
    # rpt
    path('rpt', views.RptList.as_view(), name='rpt_list'),
    path('rptdetail/<int:pk>', views.RptDetail.as_view(), name='rpt_detail'),
    path('rptupdate/<int:pk>', views.RptUpdate.as_view(), name='rpt_update'),
    path('rptdelete/<int:pk>', views.RptDelete.as_view(), name='rpt_delete'),
    path('rptcreate', views.RptCreate.as_view(), name='rpt_create'),
    # pdf
    path('editpdf/<int:id>', views.edit_pdf, name='editpdf'),
    path('monthpdf/<annee>/<mois>', views.pdf_month, name='monthpdf'),
    path('eventpdf/<int:are>/<int:rpt>/<int:event>', views.pdf_event, name='eventpdf'),
    path('searchrptmonth', views.searchrptmonth, name='searchrptmonth'),
    path('searchMonth', views.searchMonth, name='searchMonth'),
    path('archives', views.archive, name='archives'),
    path('upload/<str:arch>', views.upload, name='upload'),
    # crud ajax rpt
    path('crud_rpt/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudRpt.as_view(), name='crud_ajax_create'),
    path('ajax/crud/update/', views.UpdateCrudRpt.as_view(), name='crud_ajax_update'),
    path('ajax/crud/delete/', views.DeleteCrudRpt.as_view(), name='crud_ajax_delete'),
    path('ajax/crud/edit/', views.EditCrudRpt.as_view(), name='crud_ajax_edit'),
    path('index', views.index, name='index'),
    path('ajax_calls/search', views.autocompleteModel, name='search'),
    # are
    path('are', views.AreList.as_view(), name='are_list'),
    path('aredetail/<int:pk>', views.AreDetail.as_view(), name='are_detail'),
    path('areupdate/<int:pk>', views.AreUpdate.as_view(), name='are_update'),
    path('aredelete/<int:pk>', views.AreDelete.as_view(), name='are_delete'),
    path('arecreate', views.AreCreate.as_view(), name='are_create'),
    # iade
    path('iade', views.IadeList.as_view(), name='iade_list'),
    path('iadedetail/<int:pk>', views.IadeDetail.as_view(), name='iade_detail'),
    path('iadeupdate/<int:pk>', views.IadeUpdate.as_view(), name='iade_update'),
    path('iadedelete/<int:pk>', views.IadeDelete.as_view(), name='iade_delete'),
    path('iadecreate', views.IadeCreate.as_view(), name='iade_create'),

]

subdivision/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.urls import reverse


class HopParam(models.Model):
    name = models.CharField(max_length=100)
    adress1 = models.CharField(max_length=100)
    adress2 = models.CharField(max_length=100, blank=True, null=True)
    town = models.CharField(max_length=100)
    postalcode = models.CharField(max_length=5)
    cedex = models.CharField(max_length=10, blank=True, null=True)
    finess = models.CharField(max_length=10, blank=True, null=True)
    logo = models.ImageField(upload_to='hop', blank=True, null=True)
    tel = models.CharField(max_length=10, blank=True, null=True)
    fax = models.CharField(max_length=10, blank=True, null=True)
    villes = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Hôpital'
        verbose_name_plural = 'Hôpitaux'
        ordering = ['name']


class WebColor(models.Model):
    color = models.CharField(max_length=30, verbose_name='Couleur')
    colorHex = models.CharField(max_length=10, verbose_name='Hexa')

    def __str__(self):
        return self.color

    class Meta:
        verbose_name = 'Couleurs Web'
        ordering = ['color']


class Calendrier(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=True, blank=True)
    color = models.ForeignKey(WebColor, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Calendrier'
        verbose_name_plural = 'Calendriers'
        ordering = ['name']


class Are(models.Model):
    SECTOR = (
        ('1', 'Secteur 1'),
        ('2', 'Secteur 2'),
    )

    name = models.CharField(max_length=50, verbose_name='Nom')
    forname = models.CharField(max_length=50, verbose_name='Prénom')
    adress1 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Adresse')
    adress2 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Complément adresse')
    town = models.CharField(max_length=50, blank=True, null=True, verbose_name='Ville')
    coNum = models.CharField(max_length=20, blank=True, null=True, verbose_name='Numéro CO')
    rpps = models.CharField(max_length=20, blank=True, null=True, verbose_name='Rpps')
    postalcode = models.CharField(max_length=5, blank=True, null=True, verbose_name='Code postal')
    telmob = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Mobile')
    tel2 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Perso.')
    phone_hop = models.CharField(max_length=12, verbose_name='Poste', blank=True, null=True)
    phone_secretary = models.CharField(max_length=12, verbose_name='Secrétariat', null=True, blank=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    secteur = models.CharField(max_length=10, choices=SECTOR, verbose_name='Secteur', default=True, blank=True,
                               null=True)
    photo = models.ImageField(upload_to='are/photo', blank=True, null=True)
    signature = models.ImageField(upload_to='are/signature', blank=True, null=True)
    codepartname = models.CharField(max_length=50, blank=True, null=True)
    codepartnum = models.CharField(max_length=5, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('are_detail', kwargs={'pk': self.pk})

    @property
    def initials(self):
        return self.forname[2] + '.' + self.name[2]

    def __str__(self):
        return self.name + ' ' + self.forname

    class Meta:
        verbose_name = "Anesthésiste"
        verbose_name_plural = "Anesthésistes"
        ordering = ['name', ]


BOOL = (
    ('Oui', 'Oui'),
    ('Non', 'Non'),
)


class Rpt(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nom')
    forname = models.CharField(max_length=50, verbose_name='Prénom')
    adress1 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Adresse')
    adress2 = models.CharField(max_length=50, blank=True, null=True, verbose_name='Complément d\'adresse')
    town = models.CharField(max_length=50, blank=True, null=True, verbose_name='Ville')
    codepartname = models.CharField(max_length=50, blank=True, null=True, verbose_name='Nom Départ. CO')
    codepartnum = models.CharField(max_length=10, blank=True, null=True, verbose_name='Num. Départ. CO')
    conum = models.CharField(max_length=50, blank=True, null=True, verbose_name='Num. CO')
    rpps = models.CharField(max_length=20, blank=True, null=True, verbose_name='Num. RPPS')
    urssafnum = models.CharField(max_length=50, blank=True, null=True, verbose_name='URSSAF')
    sirennum = models.CharField(max_length=50, blank=True, null=True, verbose_name='Siren')
    postalcode = models.CharField(max_length=10, blank=True, null=True, verbose_name='Code postal')
    telmob = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Mobile')
    tel2 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Perso')
    tel3 = models.CharField(max_length=20, blank=True, null=True, verbose_name='Tél. Travail')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='Email')
    status = models.CharField(max_length=3, choices=BOOL, verbose_name='Thésé', blank=True, null=True)
    photo = models.ImageField(upload_to='rpt/photo', blank=True, null=True, verbose_name='Photo')
    assurance = models.FileField(upload_to='rpt/assurance', blank=True, null=True, verbose_name='Assurance')
    licence = models.FileField(upload_to='rpt/licence', blank=True, null=True, verbose_name='Licence')
    licence_exp_date = models.DateField(verbose_name='Date expiration licence', blank=True, null=True)
    active = models.CharField(max_length=3, choices=BOOL, verbose_name="Actif", blank=True, null=True)
    signature = models.ImageField(upload_to='rpt/signature', blank=True, null=True, )

    def get_absolute_url(self):
        return reverse('rpt_detail', kwargs={'pk': self.pk})

    @property
    def initials(self):
        return self.forname[2] + '.' + self.name[2]

    def __str__(self):
        return self.name + ' ' + self.forname

    class Meta:
        verbose_name = "Remplaçant"
        verbose_name_plural = "Remplaçants"
        ordering = ['name', ]
        unique_together = ['name', 'forname']


class Compta(models.Model):
    rpt_cost = models.IntegerField(blank=True, null=True, verbose_name='Rpt tarif')
    vac_cost_1 = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, verbose_name='Vac moins')
    vac_cost_2 = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, verbose_name='Vac plus')
    gerant = models.ForeignKey(Are, related_name='gerant', null=True, blank=True, verbose_name='Gerant',
                               on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'Comptabilite'


class Event(models.Model):
    PAYTYPE = (
        ('C', 'Chèque'),
        ('V', 'Virement'),
    )

    type = models.CharField(blank=True, null=True, default='RPT', max_length=10, verbose_name='Type')
    description = models.TextField(max_length=200, null=True, blank=True, default='', verbose_name='Résumé')
    title = models.CharField(max_length=100, default='RPT :  ', verbose_name='Titre')
    start = models.DateField(verbose_name='Début')
    start_time = models.TimeField(verbose_name='Heure début', default='00:00:00')
    end = models.DateField(verbose_name='Fin', null=True, blank=True)
    end_time = models.TimeField(verbose_name='Heure Fin', default='00:00:00')
    calendrier = models.ForeignKey(Calendrier, on_delete=models.CASCADE, blank=True, null=True,
                                   verbose_name='Type édition')
    is_cancelled = models.BooleanField(default=False, blank=True)
    all_day = models.BooleanField(default=True, blank=True)
    are = models.ForeignKey(Are, on_delete=models.DO_NOTHING, related_name='are', verbose_name='Anesthésiste',
                            null=True)
    rpt = models.ForeignKey(Rpt, on_delete=models.DO_NOTHING, related_name='rpt', verbose_name='Remplaçant', null=True)
    pay_date = models.DateField(blank=True, null=True, verbose_name='Date de paiement')
    pay_type = models.CharField(max_length=20, choices=PAYTYPE, blank=True, null=True, verbose_name='Moyen de paiement')
    pay_are = models.ForeignKey(Are, related_name='ArePay', null=True, blank=True, on_delete=models.DO_NOTHING,
                                verbose_name='Payeur')
    pay_amount = models.IntegerField(default=settings.AMOUNT_RPT, blank=True, null=True, verbose_name='Montant')
    pay_numchq = models.CharField(max_length=50, null=True, blank=True, verbose_name='N° chèque')

    def get_absolute_url(self):
        return reverse('event_detail', kwargs={'pk': self.pk})

    @property
    def jend(self):
        return self.end - timedelta(days=1)

    def __str__(self):
        return str(self.start) + ' ' + self.title

    class Meta:
        verbose_name = 'Evènement'
        verbose_name_plural = 'Evènements'
        ordering = ['start', 'end']
        unique_together = [('are', 'start'), ('rpt', 'start')]

subdivision/templates/subdivision/are/are_create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Anesthésiste{% endblock %}
{% block titre %}Mise à jour{% endblock %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="card  mt-5">
                <div class="card-header font-weight-bold">Nouvel Anesthésiste</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3 text-left">
                            <label for="id_name" class="form-label">Nom</label>
                            {{ form.name|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_forname" class="form-label">Prénom</label>
                            {{ form.forname|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="telmob" class="form-label">Tél. Mobile</label>
                            {{ form.telmob|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_tel2" class="form-label">Tél. Fixe</label>
                            {{ form.tel2|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left mt-2">
                            <label for="id_phone_hop" class="form-label">Poste</label>
                            {{ form.phone_hop|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left mt-2">
                            <label for="id_email" class="form-label">Email</label>
                            {{ form.email|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Adresse</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_adress1" class="form-label">Adresse</label>
                                {{ form.adress1|attr:"class:form-control" }}
                                <label for="id_adress2" class="form-label mt-2">Complément d'adresse</label>
                                {{ form.adress2|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_postalcode" class="form-label">Code Postal</label>
                                {{ form.postalcode|attr:"class:form-control" }}
                                <label for="id_town" class="form-label mt-2">Ville</label>
                                {{ form.town|attr:"class:form-control" }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Administration</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_rpps" class="form-label">RPPS</label>
                                {{ form.rpps|attr:"class:form-control" }}
                                <label for="id_coNum" class="form-label mt-2">Conseil de l'ordre</label>
                                {{ form.coNum|attr:"class:form-control" }}
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-sm-3">
                                <div><input class="btn btn-success pull-left" type="submit" value="Envoyer"/></div>
                            </div>
                            <div class="col-sm-3">
                                <div><a href="{% url 'are_list' %}" class="btn btn-info pull-left"
                                        role="button">Annuler</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

subdivision/templates/subdivision/are/are_detail.html
{% extends "base.html" %}
{% block title %}Détail d'un Anesthésiste{% endblock %}
{% block extrahead %}
{% endblock %}
{% block titre %}Fiche de {{ object.forname|title }} {{ object.name|upper }}{% endblock %}>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-5 text-left">
                <div class="card  mt-5">
                    <div class="card-header font-weight-bold">Détail
                        de {{ object.forname|title }} {{ object.name|upper }}
                    </div>
                    <div class="card-body">
                        <p>Nom : {{ object.name|upper }}</p>
                        <p>Prénom : {{ object.forname|title }}</p>
                        {% if object.telmob %}
                            <p>Mobile : {{ object.telmob }}</p>
                        {% else %}
                            <p class="text-danger">Mobile : Non renseigné</p>
                        {% endif %}
                        {% if object.email %}
                            <p>Email : <a href="mailto:{{ object.email }}">{{ object.email }}</a></p>
                        {% else %}
                            <p class="text-danger">Email : Non renseigné</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-5 text-left">
                <div class="card  mt-5">
                    <div class="card-body">
                        <p>Adresse : {{ object.adress1|default_if_none:'-'|title }}</p>
                        <p>Complément : {% if object.adress2 %}{{ object.adress2|title }}{% else %}-{% endif %}</p>
                        <p>Code postal : {{ object.postalcode|default_if_none:'-'|title }}</p>
                        <p>Ville : {{ object.town|default_if_none:'-'|upper }}</p>
                        <p>Tél. mobile : {{ object.telmob|default_if_none:'-' }}</p>
                        <p>Tél. travail : {{ object.phone_hop|default_if_none:'-' }}</p>
                        <p>Secteur : {{ object.secteur|default_if_none:'-' }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-5 text-left">
                <div class="card  mt-2">
                    <div class="card-header font-weight-bold">Conseil de l'Ordre</div>
                    <div class="card-body">
                        <p>Num. CO : {{ object.conum|default_if_none:'-' }}</p>
                        <p>Rpps: {{ object.rpps|default_if_none:'-' }}</p>
                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'are_list' %}" class="btn btn-primary pull-left mt-5"
           role="button">Retour</a>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

subdivision/templates/subdivision/are/are_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Mise à jour d'un Anesthésiste{% endblock %}
{% block titre %}Mise à jour{% endblock %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="card  mt-3">
                <div class="card-header font-weight-bold">
                    <div class="row  justify-content-between">
                        <div class="'col-4 ml-3">
                            Contact
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3 text-left">
                            <label for="id_name" class="form-label">Nom</label>
                            {{ form.name|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_forname" class="form-label">Prénom</label>
                            {{ form.forname|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_telmob" class="form-label">Tél. Mobile</label>
                            {{ form.telmob|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left">
                            <label for="id_tel2" class="form-label">Tél. Fixe</label>
                            {{ form.tel2|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left mt-2">
                            <label for="id_phone_hop" class="form-label">Poste</label>
                            {{ form.phone_hop|attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-3 text-left mt-2">
                            <label for="id_email" class="form-label">Email</label>
                            {{ form.email|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
            </div>
                <div class="card  mt-3">
                    <div class="card-header font-weight-bold">Adresse</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_adress1" class="form-label">Adresse</label>
                                {{ form.adress1|attr:"class:form-control" }}
                                <label for="id_adress1" class="form-label mt-2">Complément d'adresse</label>
                                {{ form.adress2|attr:"class:form-control" }}
                            </div>
                            <div class="col-sm-3 text-left">
                                <label for="id_postalcode" class="form-label">Code Postal</label>
                                {{ form.postalcode|attr:"class:form-control" }}
                                <label for="id_town" class="form-label mt-2">Ville</label>
                                {{ form.town|attr:"class:form-control" }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header font-weight-bold">Administration</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3 text-left">
                                <label for="id_rpps" class="form-label">RPPS</label>
                                {{ form.rpps|attr:"class:form-control" }}
                                <label for="id_coNum" class="form-label mt-2">Conseil de l'ordre</label>
                                {{ form.coNum|attr:"class:form-control" }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3 mt-5">
                        <div><input class="btn btn-success pull-left" type="submit" value="Envoyer"/></div>
                    </div>
                    <div class="col-sm-3 mt-5">
                        <div><a href="{% url 'are_list' %}" class="btn btn-info pull-left"
                                role="button">Annuler</a>
                        </div>
                    </div>
                </div>
        </form>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

subdivision/templates/subdivision/are/are_list.html
{% extends "base.html" %}
{% block title %}Liste des Anesthésistes{% endblock %}
{% block content %}
    <div class="container">
        <div class="card  mt-5">
            <div class="card-header font-weight-bold">Liste des Anesthésistes
                <a class="btn btn-primary btn-sm float-right" role="button"
                   href="{% url 'are_create' %}">Nouveau</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="dataTable">
                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Tél. mob.</th>
                            <th>Tél. perso.</th>
                            <th>Tél. hôp.</th>
                            <th>Email</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for are in object_list %}
                            <tr>
                                <td>{{ are.name|upper }}</td>
                                <td>{{ are.forname|capfirst }}</td>
                                <td>{% if are.telmob %}
                                    <a href="tel:{{ are.telmob }}">{% endif %}{{ are.telmob}}</a>
                                </td>
                                <td>{% if are.telmob %}
                                    <a href="tel:{{ are.tel2 }}">{% endif %}{{ are.tel2|default_if_none:"-" }}</a></td>
                                <td>{{ are.phone_hop|default_if_none:"-" }}</td>
                                <td>{% if are.email %}
                                    <a href="mailto:{{ are.email }}">{% endif %}{{ are.email|default_if_none:"-" }}</a>
                                </td>
                                <td>
                                    <a class="btn btn-info btn-sm btn-secondary fa fa-address-card"
                                       href="{% url 'are_detail' are.id %}"></a>
                                    <a class="btn btn-success btn-sm btn-secondary fa fa-edit"
                                       href="{% url 'are_update' are.id %}"></a>
                                    <a class="btn btn-danger btn-sm btn-secondary fa fa-trash"
                                       href="{% url 'are_delete' are.id %}"></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({

                "scrollY": "500px",
                "scrollCollapse": true,
                "paging": false,
                "language": {"url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"},
                "date_euro": {"url": "//cdn.datatables.net/plug-ins/1.10.20/sorting/date-euro.js"},
                autowidth: false,
                pageLength: 200,
                responsive: true,
                order: [[0, "asc"]],
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {
                        extend: 'colvis',
                        text: "Masquer",
                        postfixButtons: ['colvisRestore']
                    },
                    {
                        extend: 'csv',
                    },
                    {
                        extend: 'excel',
                    },
                    {
                        extend: 'pdf',
                    },
                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '12px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ],
            });
            $('a.toggle-vis').on('click', function (e) {
                e.preventDefault();

                // Get the column API object
                var column = table.column($(this).attr('data-column'));

                // Toggle the visibility
                column.visible(!column.visible());
            });
        });
    </script>
{% endblock %}